### ISSUE TITLE
A question on how this add-on works 

### ISSUE THREAD

**Issue by systemeFriche** [simonbroggi/blender_spreadsheet_import#5]
Hello,

First of all, Thank you for your work, it's very useful for datavisualization for instance. 
I've just two questions : 

1. Could you confirm that the modifier Geometry Node has to be added to the Data ?

<img width="289" alt="capture_2" src="https://user-images.githubusercontent.com/25347952/201136355-1e98c34d-4e06-4bf1-af02-3cb1f12e9907.png">

2. What is the object to be defined in the "Object Info" Node of the modifier ? I don't really understand with your image capture of the documentation.  

<img width="436" alt="capture_1" src="https://user-images.githubusercontent.com/25347952/201140467-d50f3dde-b297-4a56-b7cd-b1302e1dce15.png">

Thank you. 
Best regards

**Comment by simonbroggi** [comment]
Hello,
It depends on how you want to use the data.
The add-on creates a new object with geometry, and imports your data into custom attributes in the Point domain of the mesh component of that geometry.
To use the data with geometry nodes, I like to drag & drop it into an existing geometry node tree, on another object.

Here's a screenshot that might help. Note that I pinned the spreadsheet on the imported "DataFromCSV", so that I know what kind of data I am working with even when I have another object selected. The Object I create the Geometry Nodes modifier on here is just a default cube moved up one unit in edit mode such that the origin is on the 'ground'.

![usage](https://user-images.githubusercontent.com/829652/201315219-2453bc3f-530b-47c9-83e2-77cb44127e08.png)

**Comment by simonbroggi** [comment]
oh, and the quick reply to your question:
1: No
2: Probably the object that the importer generated

**Comment by systemeFriche** [comment]
Very Helpful ! Thank you very much !
Best regards
Fabien
